# Usar la imagen oficial de Python 3.11
FROM python:3.11-slim

# Establecer el directorio de trabajo en /app
WORKDIR /app

# Copiar el archivo de dependencias e instalar los paquetes
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del proyecto
COPY . .
COPY OPENAI_API_KEY.env .env

# Asegúrate de que el PDF esté disponible en el contenedor
COPY Investment_Banking_Valuation_LBOs_MA_and_IPOs_by_Joshua_Rosenbaum_Joshua_Pearl.pdf ./

# Exponer el puerto 8080 para Cloud Run
EXPOSE 8080

# Comando de arranque del contenedor usando uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
